In [1]:
import pandas as pd

In [88]:
df = pd.read_csv("fbi_final_dashboard.csv")
df

,Area,Year,Population2,Violent crime3,Murder and nonnegligent manslaughter,Rape (revised definition)4,Rape (revised definition)4.1,Robbery,Aggravated Assault,Property crime,Burglary,Larcency-theft,Motor vehicle theft
0,United States Total,2015,320896618,1234183,15883,126134,91261,328109,764057,8024115,1587564,5723488,713063
1,United States Total,2016,323127513,1283058,17250,130603,95730,332198,803007,7919035,1515096,5638455,765484
2,Northeast,2015,56184737,180474,1967,16415,11912,56202,105890,951940,157910,737087,56943
3,North Carolina,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
4,New England,2015,14710229,42121,326,4602,3374,9629,27564,257073,46260,193051,17762
...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Oregon,2016,4093465,10830,113,1721,1261,2278,6718,121345,16866,91286,13193
136,Washington,2015,7160290,20505,218,2778,2006,5450,12059,249474,51114,171393,26967
137,Washington,2016,7288000,22023,195,3077,2259,5651,13100,254653,49180,173187,32286
138,Puerto Rico,2015,3473181,7629,584,165,123,4070,2810,37717,9150,24493,4074
139,Puerto Rico,2016,3411307,7643,679,169,128,3201,3594,35201,8251,23163,3787

In [101]:
df_filtered = df[~((df['Year'] == 2015) & (df['Area'] != 'North Dakota'))]
df_filtered

,Area,Year,Population2,Violent crime3,Murder and nonnegligent manslaughter,Rape (revised definition)4,Rape (revised definition)4.1,Robbery,Aggravated Assault,Property crime,Burglary,Larcency-theft,Motor vehicle theft
1,United States Total,2016,323127513,1283058,17250,130603,95730,332198,803007,7919035,1515096,5638455,765484
3,North Carolina,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
5,New England,2016,14735525,41598,292,4505,3328,9407,27394,243769,42095,182985,18689
7,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
9,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775
...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,California,2016,39250017,174796,1930,13702,10149,54789,104375,1002070,188304,637010,176756
133,Hawaii,2016,1428557,4417,35,619,447,994,2769,42753,6017,31082,5654
135,Oregon,2016,4093465,10830,113,1721,1261,2278,6718,121345,16866,91286,13193
137,Washington,2016,7288000,22023,195,3077,2259,5651,13100,254653,49180,173187,32286
139,Puerto Rico,2016,3411307,7643,679,169,128,3201,3594,35201,8251,23163,3787

In [106]:
df_filtered["Area"].unique()

array(['United States Total', 'North Carolina', 'New England',
       'Connecticut', 'Maine', 'Massachusetts', 'New Hampshire',
       'Rhode Island', 'Vermont', 'Middle Atlantic', 'New Jersey',
       'New York', 'Pennsylvania', 'Midwest', 'East North Central',
       'Illinois', 'Indiana', 'Michigan', 'Ohio', 'Wisconsin',
       'West North Central', 'Iowa', 'Kansas', 'Minnesota', 'Missouri',
       'Nebraska', 'North Dakota', 'South Dakota', 'South', 'Alaska',
       'Arizona', 'California', 'Colorado', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Maryland',
       'South Carolina', 'Virginia', 'West Virginia',
       'East South Central', 'Alabama', 'Kentucky', 'Mississippi',
       'Tennessee', 'West South Central', 'Arkansas', 'Louisiana',
       'Oklahoma', 'Texas', 'West', 'Mountain', 'Idaho', 'Montana',
       'Nevada', 'New Mexico', 'Utah', 'Wyoming', 'Pacific', 'Hawaii',
       'Oregon', 'Washington', 'Puerto Rico'], dtype=object)

In [107]:
valid_states = [
    "North Carolina", "Connecticut", "Maine", "Massachusetts", "New Hampshire",
    "Rhode Island", "Vermont", "New Jersey", "New York", "Pennsylvania",
    "Illinois", "Indiana", "Michigan", "Ohio", "Wisconsin", "Iowa", "Kansas",
    "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota", "Alaska",
    "Arizona", "California", "Colorado", "Delaware", "District of Columbia",
    "Florida", "Georgia", "Maryland", "South Carolina", "Virginia", "West Virginia",
    "Alabama", "Kentucky", "Mississippi", "Tennessee", "Arkansas", "Louisiana",
    "Oklahoma", "Texas", "Idaho", "Montana", "Nevada", "New Mexico", "Utah",
    "Wyoming", "Puerto Rico","Hawaii","Washington","Oregon","North Dakota"
]

In [111]:
df_filtered_2 = df_filtered[df_filtered["Area"].isin(valid_states)]
df_filtered_2=df_filtered_2.reset_index()
df_filtered_2=df_filtered_2.drop(["index"],axis=1)
df_filtered_2

,Area,Year,Population2,Violent crime3,Murder and nonnegligent manslaughter,Rape (revised definition)4,Rape (revised definition)4.1,Robbery,Aggravated Assault,Property crime,Burglary,Larcency-theft,Motor vehicle theft
0,North Carolina,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456
1,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107
2,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775
3,Massachusetts,2016,6811779,25677,134,2128,1592,5365,18050,106339,19193,79088,8058
4,New Hampshire,2016,1334795,2637,17,582,423,427,1611,20194,2963,16360,871
5,Rhode Island,2016,1056426,2524,29,442,328,540,1513,20058,3788,14674,1596
6,Vermont,2016,624594,989,14,178,124,106,691,10602,2103,8217,282
7,New Jersey,2016,8944469,21914,372,1453,1089,8984,11105,138152,25284,101540,11328
8,New York,2016,19745289,74285,630,6260,4569,22316,45079,305181,39821,252669,12691
9,Pennsylvania,2016,12784227,42447,661,4433,3233,12326,23027,222795,35520,172527,14748
10,Illinois,2016,12859995,55869,941,5161,3703,18635,27565,403774,46402,331833,25539
11,Indiana,2016,6633053,24827,439,2631,1761,6168,15489,178727,33322,130575,14830
12,Michigan,2016,9928301,40298,570,4765,3304,9845,22118,230838,39704,180417,10717
13,Ohio,2016,11614373,36580,703,5014,3541,9144,21219,297726,59651,223682,14407
14,Wisconsin,2016,5779076,24347,30,4675,2587,9181,22499,147591,23940,134414,3237
15,Iowa,2016,3123899,9225,66,1268,809,2044,6038,66892,13814,51092,1986
16,Kansas,2016,2907289,11544,148,1252,952,3476,5668,72290,13292,56373,2625
17,Minnesota,2016,5506369,12654,104,1937,1309,3834,6770,101865,15080,81158,4627
18,Missouri,2016,6093000,31644,537,2554,1884,6570,21983,170549,31710,120544,18295
19,Nebraska,2016,1907116,5550,49,994,738,946,3561,43163,6444,31994,4725
20,North Dakota,2015,756835,1949,21,391,285,159,1378,17716,3296,12686,1734
21,North Carolina,2016,757952,1903,15,342,256,181,1365,17402,3243,12195,1964
22,South Dakota,2016,865454,3621,27,509,379,272,2813,17141,3000,12639,1502
23,Alaska,2016,742554,6331,59,760,760,720,4092,23873,3174,16708,1991
24,Arizona,2016,6941072,26913,380,2197,1431,8179,18726,235684,40667,168408,26609
25,California,2016,39250017,193792,1930,16896,10741,57030,114225,1031935,176530,949366,93439
26,Colorado,2016,5540545,22779,189,3222,3080,6755,14433,244955,34127,186742,24086
27,Connecticut,2016,3576452,8627,117,858,672,2908,5189,596977,94679,450668,51280
28,Delaware,2016,952065,5126,48,469,305,960,3344,42259,7795,30000,2464
29,District of Columbia,2016,681170,8107,135,869,238,3855,4950,36268,4966,28943,4359
30,Florida,2016,20612439,88700,1111,7598,5528,20175,59816,553812,100325,410352,43135
31,Georgia,2016,10310371,40990,681,3509,2528,12205,24595,309770,63344,219625,26801
32,Maryland,2016,6016447,28400,481,1756,1266,10289,15874,137445,24692,100919,11834
33,North Carolina,2016,10146788,37769,678,2849,2086,9336,24906,277765,72082,190377,15306
34,South Carolina,2016,4961119,24896,366,2387,1711,4035,18108,160928,32976,114032,13920
35,Virginia,2016,8411808,18302,484,2737,1965,4803,10278,156412,20018,126606,9788
36,West Virginia,2016,1831102,6557,81,657,468,720,5099,37487,9301,25677,2509
37,Alabama,2016,4863300,25886,407,1916,1385,4686,18877,143362,34065,97574,11723
38,Kentucky,2016,4436974,10308,260,1641,1174,3369,5038,97158,20834,66438,9886
39,Mississippi,2016,2988726,8383,238,1277,905,2397,4471,82732,23354,55054,4324
40,Tennessee,2016,6651194,42097,486,2714,1991,7813,31084,189835,40312,134404,15119
41,Arkansas,2016,2988248,16461,216,2143,1545,2120,11982,97673,23771,66747,7155
42,Louisiana,2016,4681666,26502,554,1816,1328,5576,18556,154386,34667,109380,10339
43,Oklahoma,2016,3923561,17648,245,2039,1509,3162,12202,117037,29103,75779,12155
44,Texas,2016,27862596,121042,1478,13367,9858,33317,72880,768947,148740,551151,69056
45,Arizona,2016,6931071,32583,380,3290,2452,7055,21858,206432,37736,150275,18421
46,Colorado,2016,5540545,18983,204,3555,2619,3528,11696,151850,23903,108336,19611
47,Idaho,2016,1683140,3876,49,719,529,213,2895,29357,6318,20962,2077
48,Montana,2016,1042520,3840,36,578,414,266,2960,27976,3934,21299,2743
49,Nevada,2016,2940058,19936,224,1733,1292,6340,11639,76047,18850,44017,13180
50,New Mexico,2016,2081015,14619,139,1526,1117,2737,10217,81931,17281,52907,11743
51,Utah,2016,3051217,7407,72,1520,1116,1541,4274,90058,12836,67834,9388
52,Wyoming,2016,585501,1430,20,205,150,59,1146,11460,1771,8889,800
53,Alaska,2016,741894,5966,52,1053,757,850,4011,24876,4053,17766,3057
54,California,2016,39250017,174796,1930,13702,10149,54789,104375,1002070,188304,637010,176756
55,Hawaii,2016,1428557,4417,35,619,447,994,2769,42753,6017,31082,5654
56,Oregon,2016,4093465,10830,113,1721,1261,2278,6718,121345,16866,91286,13193
57,Washington,2016,7288000,22023,195,3077,2259,5651,13100,254653,49180,173187,32286
58,Puerto Rico,2016,3411307,7643,679,169,128,3201,3594,35201,8251,23163,3787

In [112]:
all_states = df_filtered_2["Area"].unique()
all_states

array(['North Carolina', 'Connecticut', 'Maine', 'Massachusetts',
       'New Hampshire', 'Rhode Island', 'Vermont', 'New Jersey',
       'New York', 'Pennsylvania', 'Illinois', 'Indiana', 'Michigan',
       'Ohio', 'Wisconsin', 'Iowa', 'Kansas', 'Minnesota', 'Missouri',
       'Nebraska', 'North Dakota', 'South Dakota', 'Alaska', 'Arizona',
       'California', 'Colorado', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Maryland', 'South Carolina', 'Virginia',
       'West Virginia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee',
       'Arkansas', 'Louisiana', 'Oklahoma', 'Texas', 'Idaho', 'Montana',
       'Nevada', 'New Mexico', 'Utah', 'Wyoming', 'Hawaii', 'Oregon',
       'Washington', 'Puerto Rico'], dtype=object)

In [113]:
len(all_states)

52

In [115]:
state_region_map = {
    'Alabama': 'Southeast',
    'Alaska': 'West',
    'Arizona': 'West',
    'Arkansas': 'South',
    'California': 'West',
    'Colorado': 'West',
    'Connecticut': 'Northeast',
    'Delaware': 'Northeast',
    'Florida': 'Southeast',
    'Georgia': 'Southeast',
    'Hawaii': 'West',
    'Idaho': 'West',
    'Illinois': 'Midwest',
    'Indiana': 'Midwest',
    'Iowa': 'Midwest',
    'Kansas': 'Midwest',
    'Kentucky': 'Southeast',
    'Louisiana': 'South',
    'Maine': 'Northeast',
    'Maryland': 'Northeast',
    'Massachusetts': 'Northeast',
    'Michigan': 'Midwest',
    'Minnesota': 'Midwest',
    'Mississippi': 'South',
    'Missouri': 'Midwest',
    'Montana': 'West',
    'Nebraska': 'Midwest',
    'Nevada': 'West',
    'New Hampshire': 'Northeast',
    'New Jersey': 'Northeast',
    'New Mexico': 'West',
    'New York': 'Northeast',
    'North Carolina': 'Southeast',
    'North Dakota': 'Midwest',
    'Ohio': 'Midwest',
    'Oklahoma': 'South',
    'Oregon': 'West',
    'Pennsylvania': 'Northeast',
    'Rhode Island': 'Northeast',
    'South Carolina': 'Southeast',
    'South Dakota': 'Midwest',
    'Tennessee': 'Southeast',
    'Texas': 'South',
    'Utah': 'West',
    'Vermont': 'Northeast',
    'Virginia': 'Southeast',
    'Washington': 'West',
    'West Virginia': 'Southeast',
    'Wisconsin': 'Midwest',
    'Wyoming': 'West',
    "District of Columnia":'Northeast',
    "Puerto Rico":'Island'
}

In [119]:
df_filtered_2["Region"] = df_filtered_2["Area"].map(state_region_map)
df_filtered_2

,Area,Year,Population2,Violent crime3,Murder and nonnegligent manslaughter,Rape (revised definition)4,Rape (revised definition)4.1,Robbery,Aggravated Assault,Property crime,Burglary,Larcency-theft,Motor vehicle theft,Region
0,North Carolina,2016,56209510,178244,1955,16651,12219,53033,106605,909897,142720,709721,57456,Southeast
1,Connecticut,2016,3576452,8123,78,763,561,2703,4579,64664,10045,47512,7107,Northeast
2,Maine,2016,1331479,1648,20,412,300,266,950,21912,4003,17134,775,Northeast
3,Massachusetts,2016,6811779,25677,134,2128,1592,5365,18050,106339,19193,79088,8058,Northeast
4,New Hampshire,2016,1334795,2637,17,582,423,427,1611,20194,2963,16360,871,Northeast
5,Rhode Island,2016,1056426,2524,29,442,328,540,1513,20058,3788,14674,1596,Northeast
6,Vermont,2016,624594,989,14,178,124,106,691,10602,2103,8217,282,Northeast
7,New Jersey,2016,8944469,21914,372,1453,1089,8984,11105,138152,25284,101540,11328,Northeast
8,New York,2016,19745289,74285,630,6260,4569,22316,45079,305181,39821,252669,12691,Northeast
9,Pennsylvania,2016,12784227,42447,661,4433,3233,12326,23027,222795,35520,172527,14748,Northeast
10,Illinois,2016,12859995,55869,941,5161,3703,18635,27565,403774,46402,331833,25539,Midwest
11,Indiana,2016,6633053,24827,439,2631,1761,6168,15489,178727,33322,130575,14830,Midwest
12,Michigan,2016,9928301,40298,570,4765,3304,9845,22118,230838,39704,180417,10717,Midwest
13,Ohio,2016,11614373,36580,703,5014,3541,9144,21219,297726,59651,223682,14407,Midwest
14,Wisconsin,2016,5779076,24347,30,4675,2587,9181,22499,147591,23940,134414,3237,Midwest
15,Iowa,2016,3123899,9225,66,1268,809,2044,6038,66892,13814,51092,1986,Midwest
16,Kansas,2016,2907289,11544,148,1252,952,3476,5668,72290,13292,56373,2625,Midwest
17,Minnesota,2016,5506369,12654,104,1937,1309,3834,6770,101865,15080,81158,4627,Midwest
18,Missouri,2016,6093000,31644,537,2554,1884,6570,21983,170549,31710,120544,18295,Midwest
19,Nebraska,2016,1907116,5550,49,994,738,946,3561,43163,6444,31994,4725,Midwest
20,North Dakota,2015,756835,1949,21,391,285,159,1378,17716,3296,12686,1734,Midwest
21,North Carolina,2016,757952,1903,15,342,256,181,1365,17402,3243,12195,1964,Southeast
22,South Dakota,2016,865454,3621,27,509,379,272,2813,17141,3000,12639,1502,Midwest
23,Alaska,2016,742554,6331,59,760,760,720,4092,23873,3174,16708,1991,West
24,Arizona,2016,6941072,26913,380,2197,1431,8179,18726,235684,40667,168408,26609,West
25,California,2016,39250017,193792,1930,16896,10741,57030,114225,1031935,176530,949366,93439,West
26,Colorado,2016,5540545,22779,189,3222,3080,6755,14433,244955,34127,186742,24086,West
27,Connecticut,2016,3576452,8627,117,858,672,2908,5189,596977,94679,450668,51280,Northeast
28,Delaware,2016,952065,5126,48,469,305,960,3344,42259,7795,30000,2464,Northeast
29,District of Columbia,2016,681170,8107,135,869,238,3855,4950,36268,4966,28943,4359,NaN
30,Florida,2016,20612439,88700,1111,7598,5528,20175,59816,553812,100325,410352,43135,Southeast
31,Georgia,2016,10310371,40990,681,3509,2528,12205,24595,309770,63344,219625,26801,Southeast
32,Maryland,2016,6016447,28400,481,1756,1266,10289,15874,137445,24692,100919,11834,Northeast
33,North Carolina,2016,10146788,37769,678,2849,2086,9336,24906,277765,72082,190377,15306,Southeast
34,South Carolina,2016,4961119,24896,366,2387,1711,4035,18108,160928,32976,114032,13920,Southeast
35,Virginia,2016,8411808,18302,484,2737,1965,4803,10278,156412,20018,126606,9788,Southeast
36,West Virginia,2016,1831102,6557,81,657,468,720,5099,37487,9301,25677,2509,Southeast
37,Alabama,2016,4863300,25886,407,1916,1385,4686,18877,143362,34065,97574,11723,Southeast
38,Kentucky,2016,4436974,10308,260,1641,1174,3369,5038,97158,20834,66438,9886,Southeast
39,Mississippi,2016,2988726,8383,238,1277,905,2397,4471,82732,23354,55054,4324,South
40,Tennessee,2016,6651194,42097,486,2714,1991,7813,31084,189835,40312,134404,15119,Southeast
41,Arkansas,2016,2988248,16461,216,2143,1545,2120,11982,97673,23771,66747,7155,South
42,Louisiana,2016,4681666,26502,554,1816,1328,5576,18556,154386,34667,109380,10339,South
43,Oklahoma,2016,3923561,17648,245,2039,1509,3162,12202,117037,29103,75779,12155,South
44,Texas,2016,27862596,121042,1478,13367,9858,33317,72880,768947,148740,551151,69056,South
45,Arizona,2016,6931071,32583,380,3290,2452,7055,21858,206432,37736,150275,18421,West
46,Colorado,2016,5540545,18983,204,3555,2619,3528,11696,151850,23903,108336,19611,West
47,Idaho,2016,1683140,3876,49,719,529,213,2895,29357,6318,20962,2077,West
48,Montana,2016,1042520,3840,36,578,414,266,2960,27976,3934,21299,2743,West
49,Nevada,2016,2940058,19936,224,1733,1292,6340,11639,76047,18850,44017,13180,West
50,New Mexico,2016,2081015,14619,139,1526,1117,2737,10217,81931,17281,52907,11743,West
51,Utah,2016,3051217,7407,72,1520,1116,1541,4274,90058,12836,67834,9388,West
52,Wyoming,2016,585501,1430,20,205,150,59,1146,11460,1771,8889,800,West
53,Alaska,2016,741894,5966,52,1053,757,850,4011,24876,4053,17766,3057,West
54,California,2016,39250017,174796,1930,13702,10149,54789,104375,1002070,188304,637010,176756,West
55,Hawaii,2016,1428557,4417,35,619,447,994,2769,42753,6017,31082,5654,West
56,Oregon,2016,4093465,10830,113,1721,1261,2278,6718,121345,16866,91286,13193,West
57,Washington,2016,7288000,22023,195,3077,2259,5651,13100,254653,49180,173187,32286,West
58,Puerto Rico,2016,3411307,7643,679,169,128,3201,3594,35201,8251,23163,3787,Island

In [121]:
df_filtered_2.to_csv('fbi.csv', index=False)